// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYN3ZcZ0tAcSOtMwP-jneE08DJWOFji3I',
    appId: '1:971946898346:web:937ed65ea02451dc4631d3',
    messagingSenderId: '971946898346',
    projectId: 'sagtceted',
    authDomain: 'sagtceted.firebaseapp.com',
    storageBucket: 'sagtceted.firebasestorage.app',
    measurementId: 'G-32SGDLSJQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1OcNYWhFY87f11BZNs4MHwVcaWkrn3Fo',
    appId: '1:971946898346:android:1d960a460f22adb04631d3',
    messagingSenderId: '971946898346',
    projectId: 'sagtceted',
    storageBucket: 'sagtceted.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIoCuIo3ii4dbwD-S00jbKslUSlmGXFqI',
    appId: '1:971946898346:ios:b650f802111e18db4631d3',
    messagingSenderId: '971946898346',
    projectId: 'sagtceted',
    storageBucket: 'sagtceted.firebasestorage.app',
    iosBundleId: 'com.example.sagtceted',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIoCuIo3ii4dbwD-S00jbKslUSlmGXFqI',
    appId: '1:971946898346:ios:b650f802111e18db4631d3',
    messagingSenderId: '971946898346',
    projectId: 'sagtceted',
    storageBucket: 'sagtceted.firebasestorage.app',
    iosBundleId: 'com.example.sagtceted',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYN3ZcZ0tAcSOtMwP-jneE08DJWOFji3I',
    appId: '1:971946898346:web:bdecf2d3480259404631d3',
    messagingSenderId: '971946898346',
    projectId: 'sagtceted',
    authDomain: 'sagtceted.firebaseapp.com',
    storageBucket: 'sagtceted.firebasestorage.app',
    measurementId: 'G-2GX85FT0BJ',
  );
}
